language: python
python:
  - "3.6"
  - "3.7-dev"
# install dependencies, not the package itself
install:
  - pip install -r requirements.txt 
script:
  - rmd=`pwd`
  - export PYTHONPATH="$rmd:$PYTHONPATH"
  - pytest
#after_success:
#  - bash < (curl -s https://codecov.io/bash)
