version: 2
jobs:
  build:
    working_directory: ~/mykit
    docker:
      - image: circleci/python:3.7.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
          CODECOV_TOKEN: "983953a4-c383-4f0d-8e68-a31f293656e7"
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
            pip install pytest pytest-cov codecov
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            python setup.py install
            pytest --cov=./ | tee pytest-results
            codecov
      - store_test_results:
          path: pytest-results