version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7.1
jobs:
  test-3.7.1: &test-template
    working_directory: ~/mykit
    docker:
      - image: circleci/python:3.7.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
          # CODECOV_TOKEN: "983953a4-c383-4f0d-8e68-a31f293656e7"
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
            pip install pytest #pytest-cov codecov coverage
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          command: |
            python setup.py install
            pytest | tee pytest-results
      - store_test_results:
          path: pytest-results
  # test-3.6.3:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/python:3.6.3
  # test-3.5.6:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/python:3.5.6