# -*- coding: utf-8 -*-
'''include class for KPOINTS
'''

import os
from collections.abc import Iterable

from mykit.core.kmesh import kmesh_control
from mykit.core.log import verbose


class KpointsError(Exception):
    pass

# ! kmesh_control instance is used as an attribute,
# ! since vasp does not have any tag for it
class kpoints(verbose):
    '''class for manipulation KPOINTS, IBZKPT files

    At least one of kgrid, kdense, kpath, kpoints
    should be specified.

    Note:
        When auto mode check is triggered (kmode=None),
        the priority to determine the mode is:
            kpoints > kpath > kgrid > kdense

    Args:
        comment (str): the comment for KPOINTS
        kgrid (3-member list): the number of grid on each axis
        kdense (integer): the density of k grid point
            If set to non-zero value and kmode is "G", "M" or "A", the kmode will automatically be set as "A".
            If kmode is set as "L" and kpath specified, it is the number of kpoints along two special points.
        kshift (3-member list): shift off center
        kmode ("G", "M", "A", "L"): the mode of KPOINTS
            None: use explicit kpoints format
            "G": Gamma-centered
            "M": Monkhorse-Pack
            "A": fully automatic, i.e. the grid will be decided by kdense
            "L": line mode for bandstructure. kpath should be parse as well. Reciprocal vector unit is always used.
        kpath (nx3 array): the special points along the line. If specified, the mode will be changed to "L"
        kpoints (nx4 array): the explicit kpoints to parse. the fourth column is the kpoint weight.
            If specified, the explict mode will be triggered.
    '''

    def __init__(self, comment=None, kmode=None, kgrid=None, kdense=0, kshift=None, kpath=None, kpoints=None):
        try:
            assert kdense >= 0
        except AssertionError:
            raise KpointsError("kdense must not be negative")

        self.comment = comment
        # self._relatePoscar = None
        _kmode = kmode
        if isinstance(_kmode, str):
            _kmode = _kmode.upper()
        try:
            assert _kmode in [None, "G", "M", "L", "A"]
        except AssertionError:
            raise KpointsError("Unknown KPOINTS mode: {}".format(_kmode))

        # Automatic mode check when kmode is not specified
        if _kmode == None:
            if kpoints != None:
                pass
            elif kpath != None:
                _kmode = "L"
            elif kgrid != None:
                _kmode = "G"
            elif kdense > 0:
                # self.print_warn("Length(kdense) set for non-line mode. Switch to \"A\" mode.", level=1)
                _kmode = "A"
            else:
                raise KpointsError("Enter at least one of kgrid, kdense, kpath and kpoints")
        # Consistency check for each mode
        if _kmode == "L":
            if kdense == 0:
                raise KpointsError("kdense > 0 for line mode")
            if kpath == None:
                raise KpointsError("kpath should be specified for line mode")
        if _kmode == "A" and kdense == 0:
            raise KpointsError("Fully automatic mode needs positive kdense (e.g. 30)")
        if _kmode in ["G", "M"] and kgrid == None:
            raise KpointsError("kgrid should be specified for Gamma or MP mode")

        self._control = kmesh_control("vasp", kgrid=kgrid, kdense=kdense, \
            kshift=kshift, kpath=kpath, kpoints=kpoints, kmode=_kmode)

    @property
    def mode(self):
        return self._control.kmode

    def __print(self, fp):
        '''Print the kmesh in KPOINTS format to file handler

        Args:
            fp (file): the file handler
        '''
        if not self.comment:
            # TODO: automatic add comment about kpath in line mode. Or determine it in script
            print("KPOINTS generated by mykit", file=fp)
        else:
            print(self.comment, file=fp)
        _explictKs = self._control.tag_vals("vasp", "kpoints")[0]
        if _explictKs != None:
            print(len(_explictKs), file=fp)
            print("Reciprocal", file=fp)
            for _i, kp in enumerate(_explictKs):
                try:
                    print("%20.14f %20.14f %20.14f %14d" % kp, file=fp)
                except TypeError:
                    raise KpointsError("Bad explicit kpoints format: {}, index {}".format(kp, _i))
        else:
            _modeDict = {"G": "Gamma", "M": "Monkhorse-Pack", "L": "Line", "A": "Auto"}
            _kdense = self._control.tag_vals("vasp", "kdense")[0]
            _mode = self._control.tag_vals("vasp", "kmode")[0]
            if _mode == "L":
                print(int(_kdense), file=fp)
            else:
                print(0, file=fp)
            print(_modeDict[_mode], file=fp)
            if _mode in ["G", "M"]:
                _kg, _ks = self._control.tag_vals("vasp", "kgrid", "kshift")
                try:
                    print("{:3d} {:3d} {:3d}".format(*_kg), file=fp)
                except (TypeError, IndexError):
                    raise KpointsError("Bad kgrid format for G/M mode: {}".format(_kg))
                if _ks == None:
                    print(0, 0, 0, file=fp)
                else:
                    try:
                        print("{:3d} {:3d} {:3d}".format(*_ks), file=fp)
                    except (TypeError, IndexError):
                        raise KpointsError("Bad kshift format for G/M mode: {}".format(_ks))
            elif _mode == "A":
                print(int(_kdense), file=fp)
            elif _mode == "L":
                print("Reciprocal", file=fp)
                _kpath = self._control.tag_vals("vasp", "kpath")[0]
                _nSpeK = len(_kpath)
                if _nSpeK == 1:
                    raise KpointsError("At least two special points are needed to define kpath")
                for i in range(_nSpeK-1):
                    print(*_kpath[i], file=fp)
                    print(*_kpath[i+1], file=fp)
                    if i != _nSpeK - 2:
                        print('', file=fp)
            else:
                raise KpointsError("Unknown KPOINTS mode: {}".format(_mode))
        
    def print(self):
        '''Preview the KPOINTS output
        '''
        from sys import stdout
        self.__print(stdout)
        
    def write(self, pathKpoints="KPOINTS", backup=False, suffix="_bak"):
        '''Write KPOINTS to path
        '''
        _name = pathKpoints
        try: 
            assert not os.path.isdir(_name)
        except AssertionError:
            raise KpointsError("The path to write KPOINTS is a directory.")
        if os.path.isfile(_name) and backup:
            _bakname = _name + suffix.strip()
            os.rename(_name, _bakname)
        with open(_name, 'w') as f:
            self.__print(f)

    @classmethod
    def read_from_kpoints(cls, pathKpoints="KPOINTS"):
        pass

    @classmethod
    def read_from_ibzkpt(cls, pathKpoints="IBZKPT"):
        pass

    # * Factory methods to write kpath of particular crystal
    # * Name with kpath_(bravis)
